INSERT INTO blood_norms (leukocyty_n_d, erytrocyty_n_d, hemoglobina_n_d, hematokryt_n_d, mcv_n_d, mch_n_d, 
  mchc_n_d, plytki_krwi_n_d, rdw_sd_n_d, rdw_cv_n_d, pdw_n_d, mpv_n_d, p_lcr_n_d, pct_n_d, neutrofile_n_d, 
  limfocyty_n_d, monocyty_n_d, eozynofile_n_d, bazofile_n_d, ferrytyna_n_d, tsh_n_d, ft3_n_d, ft4_n_d, 
  leukocyty_n_g, erytrocyty_n_g, hemoglobina_n_g, hematokryt_n_g, mcv_n_g, mch_n_g, mchc_n_g, 
  plytki_krwi_n_g, rdw_sd_n_g, rdw_cv_n_g, pdw_n_g, mpv_n_g, p_lcr_n_g, pct_n_g, neutrofile_n_g, 
  limfocyty_n_g, monocyty_n_g, eozynofile_n_g, bazofile_n_g, ferrytyna_n_g, tsh_n_g, ft3_n_g, ft4_n_g) 
VALUES (4.0,3.9,11.2,34.1,79.4,25.6,32.2,150.0,36.4,11.7,9.8,9.4,19.1,0.17,2.00,1.00,0.2,0.02,0.02,13.0,
  0.270,2.00,0.93,10.0,5.2,15.7,44.9,94.8,32.2,35.5,400.0,46.3,14.4,16.2,12.5,46.6,0.35,7.0,3.0,1.0,0.5,
  0.1,150.0,4.2,4.4,1.7);

INSERT INTO advices (leukocyty_n_d, erytrocyty_n_d, hemoglobina_n_d, hematokryt_n_d, mcv_n_d, mch_n_d, 
  mchc_n_d, plytki_krwi_n_d, rdw_sd_n_d, rdw_cv_n_d, pdw_n_d, mpv_n_d, p_lcr_n_d, pct_n_d, neutrofile_n_d, 
  limfocyty_n_d, monocyty_n_d, eozynofile_n_d, bazofile_n_d, ferrytyna_n_d, tsh_n_d, ft3_n_d, ft4_n_d, 
  leukocyty_n_g, erytrocyty_n_g, hemoglobina_n_g, hematokryt_n_g, mcv_n_g, mch_n_g, mchc_n_g, 
  plytki_krwi_n_g, rdw_sd_n_g, rdw_cv_n_g, pdw_n_g, mpv_n_g, p_lcr_n_g, pct_n_g, neutrofile_n_g, 
  limfocyty_n_g, monocyty_n_g, eozynofile_n_g, bazofile_n_g, ferrytyna_n_g, tsh_n_g, ft3_n_g, ft4_n_g)
VALUES ('niski poziom leukocytów - leukopenia', 
'niski poziom erytrocytów',
'niski poziom hemoglobiny',
'niski poziom hematokryt',
'niski poziom mcv',
'niski poziom mch',
'niski poziom mchc',
'niski poziom płytek krwi - Trombocytopenia',
'niski poziom rdw-sd',
'niski poziom rdw-cv',
'niski poziom pdw',
'niski poziom mpv',
'niski poziom p-lcr',
'niski poziom pct',
'niski poziom neutrofili',
'niski poziom limfocytów',
'niski poziom monocytów',
'niski poziom eozyfilów',
'niski poziom bazofilów',
'niski poziom ferrytyny',
'niski poziom tsh',
'niski poziom ft3',
'niski poziom ft4',
'wysoki poziom leukocytów - leukocytoza',
'wysoki poziom erytrocytów',
'wysoki poziom hemoglobiny - hemoglobinemia', 
'wysoki poziom hematokryt',
'wysoki poziom mcv',
'wysoki poziom mch',
'wysoki poziom mchc',
'wysoki poziom płytek krwi - Trombocytoza',
'wysoki poziom rdw-sd',
'wysoki poziom rdw-cv',
'wysoki poziom pdw',
'wysoki poziom mpv',
'wysoki poziom p-lcr',
'wysoki poziom pct',
'wysoki poziom neutrofili',
'wysoki poziom limfocytów',
'wysoki poziom monocytów',
'wysoki poziom eozyfilów',
'wysoki poziom bazofilów',
'wysoki poziom ferrytyny',
'wysoki poziom tsh',
'wysoki poziom ft3',
'wysoki poziom ft4'
);




INSERT INTO advices (leukocyty_n_d, erytrocyty_n_d, hemoglobina_n_d, hematokryt_n_d, mcv_n_d, mch_n_d, 
  mchc_n_d, plytki_krwi_n_d, rdw_sd_n_d, rdw_cv_n_d, pdw_n_d, mpv_n_d, p_lcr_n_d, pct_n_d, neutrofile_n_d, 
  limfocyty_n_d, monocyty_n_d, eozynofile_n_d, bazofile_n_d, ferrytyna_n_d, tsh_n_d, ft3_n_d, ft4_n_d, 
  leukocyty_n_g, erytrocyty_n_g, hemoglobina_n_g, hematokryt_n_g, mcv_n_g, mch_n_g, mchc_n_g, 
  plytki_krwi_n_g, rdw_sd_n_g, rdw_cv_n_g, pdw_n_g, mpv_n_g, p_lcr_n_g, pct_n_g, neutrofile_n_g, 
  limfocyty_n_g, monocyty_n_g, eozynofile_n_g, bazofile_n_g, ferrytyna_n_g, tsh_n_g, ft3_n_g, ft4_n_g) 
VALUES ('https://www.poradnikzdrowie.pl/zdrowie/uklad-krwionosny/leukopenia-mala-liczba-leukocytow-przyczyny-objawy-i-leczenie-aa-1gSu-4mM9-h4qK.html',
'https://wylecz.to/badania-laboratoryjne/badanie-erytrocyty-we-krwi/',
'https://wylecz.to/badania-laboratoryjne/niska-hemoglobina-o-czym-swiadczy-niski-poziom-hemoglobiny/',
'http://www.medonet.pl/badania,hematokryt--hct----norma-badania--co-oznacza-niski-poziom-,artykul,1570103.html',
'https://zdrowie.tvn.pl/a/mcv-w-morfologii-normy-podwyzszone-i-obnizone-stezenie',
'https://www.poradnikzdrowie.pl/sprawdz-sie/badania/mch-morfologia-norma-mch-podwyzszone-i-obnizone-mch-aa-ybea-2D6s-jb3Y.html',
'https://www.poradnikzdrowie.pl/sprawdz-sie/badania/mchc-niska-lub-wysoka-wartosc-co-oznacza-aa-oivF-XMbF-JjSa.html',
'https://www.poradnikzdrowie.pl/zdrowie/uklad-krwionosny/trombocytopenia-maloplytkowosc-mala-liczba-plytek-krwi-aa-gwCt-uoy7-tmfd.html',
'https://parenting.pl/rdw-sd-charakterystyka-o-czym-nas-informuje-norma-zbyt-niskie-i-zbyt-wysokie',
'https://www.medme.pl/artykuly/rdw-cv-co-oznacza-podwyzszony-a-co-obnizony-wynik-w-morfologii,67660.html',
'https://www.medme.pl/artykuly/pdw-morfologia-krwi-interpretacja-wyniku-i-norma-badania,67476.html',
'https://parenting.pl/mpv-morfologia-czym-jest-spadek-mpv-wzrost-mpv',
'https://portal.abczdrowie.pl/badanie-p-lcr-charakterystyka-normy',
'https://www.poradnikzdrowie.pl/sprawdz-sie/badania/prokalcytonina-pct-normy-i-wyniki-badania-aa-5gM9-PEpJ-vpji.html',
'https://www.poradnikzdrowie.pl/sprawdz-sie/badania/neutrofile-normy-co-oznacza-podwyzszony-lub-obnizony-poziom-neutrofilo-aa-EzVK-Qfpg-QhBs.html',
'http://www.medonet.pl/zdrowie/zdrowie-dla-kazdego,limfocyty---powyzej-i-ponizej-normy--podwyzszone-i-obnizone-,artykul,1721476.html',
'https://polki.pl/zdrowie/diagnostyka,monocyty-norma-podwyzszone-niskie-ponizej-normy-w-ciazy,10422979,artykul.html',
'https://www.poradnikzdrowie.pl/sprawdz-sie/badania/eozynofile-eozynocyty-eos-podwyzszone-lub-ponizej-normy-aa-sAcV-QXWn-EJti.html',
'https://zdrowie.tvn.pl/a/bazofile-we-krwi-przyczyny-niskiego-i-wysokiego-poziomu-o-czym-swiadcza-wyniki-poza-norma',
'https://portal.abczdrowie.pl/ferrytyna',
'https://portal.abczdrowie.pl/niskie-tsh-przyczyny-znaczenie',
'https://www.medme.pl/artykuly/co-oznacza-podwyzszone-i-niskie-ft3-i-jak-wyglada-badanie,69132.html',
'https://wylecz.to/badania-laboratoryjne/badanie-ft4-wolna-tyroksyna/',
'http://zdrowie.gazeta.pl/Zdrowie/7,101580,22992978,gdy-leukocytow-jest-za-duzo-leukocytoza-poziom-leukocytow.html',
'https://wylecz.to/badania-laboratoryjne/badanie-erytrocyty-we-krwi/',
'https://wylecz.to/choroby-krwi/wysoki-poziom-hemoglobiny-hemoglobinemia/',
'http://www.medonet.pl/badania,hematokryt--hct----norma-badania--co-oznacza-niski-poziom-,artykul,1570103.html',
'https://zdrowie.tvn.pl/a/mcv-w-morfologii-normy-podwyzszone-i-obnizone-stezenie',
'https://www.poradnikzdrowie.pl/sprawdz-sie/badania/mch-morfologia-norma-mch-podwyzszone-i-obnizone-mch-aa-ybea-2D6s-jb3Y.html',
'https://www.poradnikzdrowie.pl/sprawdz-sie/badania/mchc-niska-lub-wysoka-wartosc-co-oznacza-aa-oivF-XMbF-JjSa.html',
'https://www.poradnikzdrowie.pl/zdrowie/uklad-krwionosny/naplytkowosc-trombocytoza-duza-liczba-plytek-krwi-przyczyny-objawy-i-l-aa-qLnf-Zbm9-Z3zw.html',
'https://parenting.pl/rdw-sd-charakterystyka-o-czym-nas-informuje-norma-zbyt-niskie-i-zbyt-wysokie',
'https://www.medme.pl/artykuly/rdw-cv-co-oznacza-podwyzszony-a-co-obnizony-wynik-w-morfologii,67660.html',
'https://www.medme.pl/artykuly/pdw-morfologia-krwi-interpretacja-wyniku-i-norma-badania,67476.html',
'https://parenting.pl/mpv-morfologia-czym-jest-spadek-mpv-wzrost-mpv',
'https://portal.abczdrowie.pl/badanie-p-lcr-charakterystyka-normy',
'https://www.poradnikzdrowie.pl/sprawdz-sie/badania/prokalcytonina-pct-normy-i-wyniki-badania-aa-5gM9-PEpJ-vpji.html',
'https://www.poradnikzdrowie.pl/sprawdz-sie/badania/neutrofile-normy-co-oznacza-podwyzszony-lub-obnizony-poziom-neutrofilo-aa-EzVK-Qfpg-QhBs.html',
'http://www.medonet.pl/zdrowie/zdrowie-dla-kazdego,limfocyty---powyzej-i-ponizej-normy--podwyzszone-i-obnizone-,artykul,1721476.html',
'https://polki.pl/zdrowie/diagnostyka,monocyty-norma-podwyzszone-niskie-ponizej-normy-w-ciazy,10422979,artykul.html',
'https://www.poradnikzdrowie.pl/sprawdz-sie/badania/eozynofile-eozynocyty-eos-podwyzszone-lub-ponizej-normy-aa-sAcV-QXWn-EJti.html',
'https://zdrowie.tvn.pl/a/bazofile-we-krwi-przyczyny-niskiego-i-wysokiego-poziomu-o-czym-swiadcza-wyniki-poza-norma',
'https://portal.abczdrowie.pl/ferrytyna',
'https://wylecz.to/badania-laboratoryjne/wysokie-tsh-o-czym-swiadczy-poziom-tsh-powyzej-normy/',
'https://www.medme.pl/artykuly/co-oznacza-podwyzszone-i-niskie-ft3-i-jak-wyglada-badanie,69132.html',
'https://wylecz.to/badania-laboratoryjne/badanie-ft4-wolna-tyroksyna/'
);
